version: '3.11'

services:
  app:
    build: .
    ports:
      - "1234:1234"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
